use crate::bus::Bus;
use crate::cpu::AddressingMode;

struct DisasmLine {
    addr: u16,
    bytes_hex: String,
    text: String
}

fn decode_opcode(opcode: u8) -> Option<(&'static str, AddressingMode, u8)> {
    use AddressingMode::*;
    match opcode {
        0x00 => Some(("BRK", Implied, 1)),
        0x01 => Some(("ORA", IndirectX, 2)),
        0x05 => Some(("ORA", ZeroPage, 2)),
        0x06 => Some(("ASL", ZeroPage, 2)),
        0x08 => Some(("PHP", Implied, 1)),
        0x09 => Some(("ORA", Immediate, 2)),
        0x0A => Some(("ASL", Implied, 1)),
        0x0D => Some(("ORA", Absolute, 3)),
        0x0E => Some(("ASL", Absolute, 3)),
        0x10 => Some(("BPL", Immediate, 2)),
        0x11 => Some(("ORA", IndirectY, 2)),
        0x15 => Some(("ORA", ZeroPageX, 2)),
        0x16 => Some(("ASL", ZeroPageX, 2)),
        0x18 => Some(("CLC", Implied, 1)),
        0x19 => Some(("ORA", AbsoluteY, 3)),
        0x1D => Some(("ORA", AbsoluteX, 3)),
        0x1E => Some(("ASL", AbsoluteX, 3)),
        0x20 => Some(("JSR", Absolute, 3)),
        0x21 => Some(("AND", IndirectX, 2)),
        0x24 => Some(("BIT", ZeroPage, 2)),
        0x25 => Some(("AND", ZeroPage, 2)),
        0x26 => Some(("ROL", ZeroPage, 2)),
        0x28 => Some(("PLP", Implied, 1)),
        0x29 => Some(("AND", Immediate, 2)),
        0x2A => Some(("ROL", Implied, 1)),
        0x2C => Some(("BIT", Absolute, 3)),
        0x2D => Some(("AND", Absolute, 3)),
        0x2E => Some(("ROL", Absolute, 3)),
        0x30 => Some(("BMI", Immediate, 2)),
        0x31 => Some(("AND", IndirectY, 2)),
        0x35 => Some(("AND", ZeroPageX, 2)),
        0x36 => Some(("ROL", ZeroPageX, 2)),
        0x38 => Some(("SEC", Implied, 1)),
        0x39 => Some(("AND", AbsoluteY, 3)),
        0x3D => Some(("AND", AbsoluteX, 3)),
        0x3E => Some(("ROL", AbsoluteX, 3)),
        0x40 => Some(("RTI", Implied, 1)),
        0x41 => Some(("EOR", IndirectX, 2)),
        0x45 => Some(("EOR", ZeroPage, 2)),
        0x46 => Some(("LSR", ZeroPage, 2)),
        0x48 => Some(("PHA", Implied, 1)),
        0x49 => Some(("EOR", Immediate, 2)),
        0x4A => Some(("LSR", Implied, 1)),
        0x4C => Some(("JMP", Absolute, 3)),
        0x4D => Some(("EOR", Absolute, 3)),
        0x4E => Some(("LSR", Absolute, 3)),
        0x50 => Some(("BVC", Immediate, 2)),
        0x51 => Some(("EOR", IndirectY, 2)),
        0x55 => Some(("EOR", ZeroPageX, 2)),
        0x56 => Some(("LSR", ZeroPageX, 2)),
        0x58 => Some(("CLI", Implied, 1)),
        0x59 => Some(("EOR", AbsoluteY, 3)),
        0x5D => Some(("EOR", AbsoluteX, 3)),
        0x5E => Some(("LSR", AbsoluteX, 3)),
        0x60 => Some(("RTS", Implied, 1)),
        0x61 => Some(("ADC", IndirectX, 2)),
        0x65 => Some(("ADC", ZeroPage, 2)),
        0x66 => Some(("ROR", ZeroPage, 2)),
        0x68 => Some(("PLA", Implied, 1)),
        0x69 => Some(("ADC", Immediate, 2)),
        0x6A => Some(("ROR", Implied, 1)),
        0x6C => Some(("JMP", Absolute, 3)), // indirect, but 3 bytes total
        0x6D => Some(("ADC", Absolute, 3)),
        0x6E => Some(("ROR", Absolute, 3)),
        0x70 => Some(("BVS", Immediate, 2)),
        0x71 => Some(("ADC", IndirectY, 2)),
        0x75 => Some(("ADC", ZeroPageX, 2)),
        0x76 => Some(("ROR", ZeroPageX, 2)),
        0x78 => Some(("SEI", Implied, 1)),
        0x79 => Some(("ADC", AbsoluteY, 3)),
        0x7D => Some(("ADC", AbsoluteX, 3)),
        0x7E => Some(("ROR", AbsoluteX, 3)),
        0x81 => Some(("STA", IndirectX, 2)),
        0x84 => Some(("STY", ZeroPage, 2)),
        0x85 => Some(("STA", ZeroPage, 2)),
        0x86 => Some(("STX", ZeroPage, 2)),
        0x88 => Some(("DEY", Implied, 1)),
        0x8A => Some(("TXA", Implied, 1)),
        0x8C => Some(("STY", Absolute, 3)),
        0x8D => Some(("STA", Absolute, 3)),
        0x8E => Some(("STX", Absolute, 3)),
        0x90 => Some(("BCC", Immediate, 2)),
        0x91 => Some(("STA", IndirectY, 2)),
        0x94 => Some(("STY", ZeroPageX, 2)),
        0x95 => Some(("STA", ZeroPageX, 2)),
        0x96 => Some(("STX", ZeroPageY, 2)),
        0x98 => Some(("TYA", Implied, 1)),
        0x99 => Some(("STA", AbsoluteY, 3)),
        0x9A => Some(("TXS", Implied, 1)),
        0x9D => Some(("STA", AbsoluteX, 3)),
        0xA0 => Some(("LDY", Immediate, 2)),
        0xA1 => Some(("LDA", IndirectX, 2)),
        0xA2 => Some(("LDX", Immediate, 2)),
        0xA4 => Some(("LDY", ZeroPage, 2)),
        0xA5 => Some(("LDA", ZeroPage, 2)),
        0xA6 => Some(("LDX", ZeroPage, 2)),
        0xA8 => Some(("TAY", Implied, 1)),
        0xA9 => Some(("LDA", Immediate, 2)),
        0xAA => Some(("TAX", Implied, 1)),
        0xAC => Some(("LDY", Absolute, 3)),
        0xAD => Some(("LDA", Absolute, 3)),
        0xAE => Some(("LDX", Absolute, 3)),
        0xB0 => Some(("BCS", Immediate, 2)),
        0xB1 => Some(("LDA", IndirectY, 2)),
        0xB4 => Some(("LDY", ZeroPageX, 2)),
        0xB5 => Some(("LDA", ZeroPageX, 2)),
        0xB6 => Some(("LDX", ZeroPageY, 2)),
        0xB8 => Some(("CLV", Implied, 1)),
        0xB9 => Some(("LDA", AbsoluteY, 3)),
        0xBA => Some(("TSX", Implied, 1)),
        0xBC => Some(("LDY", AbsoluteX, 3)),
        0xBD => Some(("LDA", AbsoluteX, 3)),
        0xBE => Some(("LDX", AbsoluteY, 3)),
        0xC0 => Some(("CPY", Immediate, 2)),
        0xC1 => Some(("CMP", IndirectX, 2)),
        0xC4 => Some(("CPY", ZeroPage, 2)),
        0xC5 => Some(("CMP", ZeroPage, 2)),
        0xC6 => Some(("DEC", ZeroPage, 2)),
        0xC8 => Some(("INY", Implied, 1)),
        0xC9 => Some(("CMP", Immediate, 2)),
        0xCA => Some(("DEX", Implied, 1)),
        0xCC => Some(("CPY", Absolute, 3)),
        0xCD => Some(("CMP", Absolute, 3)),
        0xCE => Some(("DEC", Absolute, 3)),
        0xD0 => Some(("BNE", Immediate, 2)),
        0xD1 => Some(("CMP", IndirectY, 2)),
        0xD5 => Some(("CMP", ZeroPageX, 2)),
        0xD6 => Some(("DEC", ZeroPageX, 2)),
        0xD8 => Some(("CLD", Implied, 1)),
        0xD9 => Some(("CMP", AbsoluteY, 3)),
        0xDD => Some(("CMP", AbsoluteX, 3)),
        0xDE => Some(("DEC", AbsoluteX, 3)),
        0xE0 => Some(("CPX", Immediate, 2)),
        0xE1 => Some(("SBC", IndirectX, 2)),
        0xE4 => Some(("CPX", ZeroPage, 2)),
        0xE5 => Some(("SBC", ZeroPage, 2)),
        0xE6 => Some(("INC", ZeroPage, 2)),
        0xE8 => Some(("INX", Implied, 1)),
        0xE9 => Some(("SBC", Immediate, 2)),
        0xEA => Some(("NOP", Implied, 1)),
        0xEC => Some(("CPX", Absolute, 3)),
        0xED => Some(("SBC", Absolute, 3)),
        0xEE => Some(("INC", Absolute, 3)),
        0xF0 => Some(("BEQ", Immediate, 2)),
        0xF1 => Some(("SBC", IndirectY, 2)),
        0xF5 => Some(("SBC", ZeroPageX, 2)),
        0xF6 => Some(("INC", ZeroPageX, 2)),
        0xF8 => Some(("SED", Implied, 1)),
        0xF9 => Some(("SBC", AbsoluteY, 3)),
        0xFD => Some(("SBC", AbsoluteX, 3)),
        0xFE => Some(("INC", AbsoluteX, 3)),
        _ => None,
    }
}

fn format_operand(mnemonic: &str, mode: &AddressingMode, bytes: &[u8]) -> String {
    use AddressingMode::*;
    match mode {
        Implied => mnemonic.to_string(),
        Immediate => format!("{} #${:02X}", mnemonic, bytes[1]),
        ZeroPage => format!("{} ${:02X}", mnemonic, bytes[1]),
        ZeroPageX => format!("{} ${:02X},X", mnemonic, bytes[1]),
        ZeroPageY => format!("{} #${:02X},Y", mnemonic, bytes[1]),
        Absolute => format!("{} ${:02X}{:02X}", mnemonic, bytes[2], bytes[1]),
        AbsoluteX => format!("{} ${:02X}{:02X},X", mnemonic, bytes[2], bytes[1]),
        AbsoluteY => format!("{} ${:02X}{:02X},Y", mnemonic, bytes[2], bytes[1]),
        IndirectX => format!("{} (${:02X},X)", mnemonic, bytes[1]),
        IndirectY => format!("{} (${:02X}),Y", mnemonic, bytes[1]),
    }
}

pub fn disassemble_range() {

}